fix: RTL chevron issue
imfing/hextra pull request #302
Opened 2024-02-19 22:17 UTC by Goudarz

2024-02-19 23:05 UTC, imfing requested changes
in this case, we could just use Tailwind CSS to rotate the chevron icon:

[Handling Hover, Focus, and Other States - Tailwind CSS](https://tailwindcss.com/docs/hover-focus-and-other-states#rtl-support)

you may need to run `npm run build:css` to compile the CSS styles and commit it after the above changes have been made.

2024-02-19 23:05 UTC, imfing commented on layouts/partials/breadcrumb.html
> +      {{ end }}
```suggestion
      {{- partial "utils/icon.html" (dict "name" "chevron-right" "attributes" "class=\"w-3.5 shrink-0 rtl:-rotate-180\"") -}}
```

2024-02-19 23:05 UTC, imfing commented on layouts/partials/components/pager.html
> +        {{ end }}
```suggestion
        {{- partial "utils/icon.html" (dict "name" "chevron-right" "attributes" "class=\"inline h-5 shrink-0 rtl:-rotate-180\"") -}}
```

2024-02-20 13:50 UTC, Goudarz commented
@imfing, The files has been updated according to the documentation. 👍

2024-02-20 22:27 UTC, imfing approved these changes
@Goudarz awesome, thank you!

2024-02-20 22:27 UTC, merged