feat: support customize flexsearch tokenize option && inject hextra p…
imfing/hextra pull request #319
Opened 2024-03-13 17:53 UTC by loenvom

…arams to js env

2024-03-13 23:16 UTC, imfing commented on exampleSite/hugo.yaml
> +      # to know more: https://github.com/nextapps-de/flexsearch/blob/540d25e97117c73b1ce9e50e54423e5d8140a710/README.md#tokenizer
```suggestion
      # https://github.com/nextapps-de/flexsearch/#tokenizer-prefix-search
```

2024-03-13 23:19 UTC, imfing requested changes
Thanks, I think it's a great addition to the search feature.

We could leverage Hugo templates in the `flexsearch.js` rather than injecting a global variable.

2024-03-13 23:19 UTC, imfing commented on assets/js/flexsearch.js
> +    const tokenize = window?.hextra?.search?.flexsearch?.tokenize ?? 'forward'
we could use hugo template here

for example: https://github.com/loenvom/hextra/blob/feat/custom_flex_search_tokenize/assets/js/flexsearch.js#L20

2024-03-13 23:19 UTC, imfing commented on layouts/partials/scripts.html
> +<script>
if we use hugo template in the `flexsearch.js`, then no need to inject this global variable here

2024-03-14 16:49 UTC, loenvom commented
I'am glad that you like it! I have already submitted a new commit, please help review it again. ✨

2024-03-17 18:49 UTC, imfing approved these changes
great! looks good to me 👍

2024-03-17 18:50 UTC, merged

2024-03-17 18:57 UTC, imfing commented
We also need to document this new option once it's release.