add support for Umami analytics
imfing/hextra pull request #328
Opened 2024-03-21 11:26 UTC by marten-seemann

Fixes #327.

2024-03-22 20:45 UTC, imfing commented
Hi, thank you for the PR. 

I don't plan to include this in the next release, but will kep this open for the future.

2024-03-22 20:50 UTC, marten-seemann commented
@imfing Any changes you’d like to see to this PR? Any chance this could be included in the next release? I’ve already tested the code and it works, would be great if I could remove my fork with the next release.

2024-03-28 07:45 UTC, imfing commented
Just a side note: for current versions (`0.7.x`), the tracking code could be placed under `layouts/partials/custom/head-end.html` of your site

```html
<script async defer src="https://url" data-website-id="id" ></script>
```

2024-03-28 07:47 UTC, imfing commented on layouts/partials/head.html
> +  {{- if and hugo.IsProduction .Site.Params.umami.serverURL .Site.Params.umami.id }}
I suggest placing it under `analytics`:

```yaml
params:
  analytics:
    # https://github.com/umami-software/umami
    umami:
      server: https://server-url
      # script: umami.js
      id: "site-id"
```

2024-03-28 07:48 UTC, imfing requested changes
Per above, also could you create another PR to add documentation for this?

2024-08-18 13:48 UTC, closed without merging