add cellular_raza to showcase exampleSite
imfing/hextra pull request #498
Opened 2024-11-13 08:12 UTC by jonaspleyer

Hi,
Thank you for this really nice hugo theme. I would love to add the documentation website of my simulation tool `cellular_raza` to the showcase site.
I was unsure where to put the image so I simply included it in the static folder but I assume that this is not the correct place. Please let me know where to put it.

2024-11-13 17:59 UTC, imfing requested changes
@jonaspleyer thank you, the project site looks fantastic! 

I'd prefer uploading images to GitHub PR or Issues comment, and use the link generated by GitHub (I did that already, please check the comment below)

2024-11-13 17:59 UTC, imfing commented on exampleSite/static/images/cellular_raza.png
please remove this

2024-11-13 17:59 UTC, imfing commented on exampleSite/content/showcase/index.md
> +        image="/images/cellular_raza.png"
```suggestion
        image="https://github.com/user-attachments/assets/f24c6455-b70a-419b-b025-e3d60101b673"
```

2024-11-14 09:09 UTC, jonaspleyer commented on exampleSite/static/images/cellular_raza.png
Thanks for the changes. I have commited them.

2024-11-14 11:19 UTC, merged